### ISSUE TITLE
Double subscriptions when using useTracker in lazy components

### ISSUE THREAD

**Issue by ksinas** [meteor/react-packages#324]
When using `useTracker` in lazy components I noticed that sometimes data get subscribed, unsubscribed and subscribed again.

This happens because [useMemo][L122] and [useEffect][L127] sometimes gets called synchronously, thus [comp.stop()][L121] gets called too late, resulting in second subscription.

[L122]: https://github.com/meteor/react-packages/blob/501f0ecfbd694d38f35afde4c96b449b69f8b60e/packages/react-meteor-data/useTracker.ts#L112
[L127]: https://github.com/meteor/react-packages/blob/501f0ecfbd694d38f35afde4c96b449b69f8b60e/packages/react-meteor-data/useTracker.ts#L127
[L121]: https://github.com/meteor/react-packages/blob/501f0ecfbd694d38f35afde4c96b449b69f8b60e/packages/react-meteor-data/useTracker.ts#L121

**Comment by CaptainN** [comment]
useMemo and useEffect (given the same set of deps) should not ever be called synchronously. Can you point me to some information about cases where it might?

**Comment by CaptainN** [comment]
A simple rewrite might help:

```
useMemo(() => {
    // To jive with the lifecycle interplay between Tracker/Subscribe, run the
    // reactive function in a computation, then stop it, to force flush cycle.
    const comp = Tracker.nonreactive(
      () => Tracker.autorun((c: Tracker.Computation) => {
        if (c.firstRun) data = refs.reactiveFn();
      })
    );
    // To avoid creating side effects in render, stop the computation immediately
    Meteor.defer(() => { comp.stop() });
    if (Meteor.isDevelopment) {
      checkCursor(data);
    }
  }, deps);

  useEffect(() => {
    const computation =  Tracker.nonreactive(
      () => Tracker.autorun((c) => {
        setData(refs.reactiveFn(c));
      })
    );
    return () => {
      computation.stop();
    }
  }, deps);

**Comment by CaptainN** [comment]
Anyway, I can fix this if needed, but I'll need a reproduction.

**Comment by ksinas** [comment]
Actually, the problem is with Meteor.defer. I replicated it and wrote a simple app which shows the sequence of actions.
You can see that they are called in different sequence when using a lazy component
https://codesandbox.io/s/delicate-hooks-61067?file=/src/App.js

**Comment by ksinas** [comment]
What if something like this? If we avoid stopping initial computation, then we would also preserve the same output from the first computation. Is there any negative consequence to this approach?

```js
const useTracker = (reactiveFn, deps) => {
  let [data, setData] = useState();
  const { current: refs } = useRef({ reactiveFn, mounted: false, computation: null });
  refs.reactiveFn = reactiveFn;
  refs.data = data;

  useMemo(() => {
    refs.computation = Tracker.nonreactive(
      () => Tracker.autorun((c: Tracker.Computation) => {
       // keep the outorun alive, but do not create side effects in render
        refs.intermediateData = refs.reactiveFn();
        if (Meteor.isDevelopment) {
          checkCursor(refs.intermediateData);
        }
        if (c.firstRun) {
          refs.data = refs.intermediateData
          delete refs.intermediateData;
        } else if (refs.mounted) {
          setData(refs.intermediateData)
          delete refs.intermediateData;
        }
      })
    );
  }, deps);

  useEffect(() => {
    refs.mounted = true;
    if (refs.intermediateData) {
      setData(refs.intermediateData)
      delete refs.intermediateData;
    } else {
      setData(refs.data)
    }
    return () => {
      refs.mounted = false;
      refs.computation.stop()
      refs.computation = null;
    }
  }, deps);
  return refs.data;
}
```

**Comment by CaptainN** [comment]
Interesting. Replacing meteorDefer with setTimeout fixes your test case. But I don't know if that's a workable solution in production, because if I understand it correctly, browser limit the smallest setTimeout interval to 4ms, and I don't know how long it takes in minimum for useEffect to run after render.

I can come up with a solution without using setTimeout, but it's a bummer that Meteor.defer doesn't work in this case. Maybe this is something that can be fixed on that side?

**Comment by ksinas** [comment]
I wouldn't change it to setTimeout. You could just always stop the computation on the start of the useEffect. But how about my previous suggestion? It solves 2 issues instead.

**Comment by CaptainN** [comment]
Your suggestion makes 100% sense, except when concurrent mode is used, which is the real problem with all this. Your computation.stop() would never be called for 3 out of 4 renders created when using concurrent mode, because in that mode the render body is called multiple times, but useEffect is only called once on the instance that gets "committed" (sometimes we say "mounted").

Meteor.subscribe actually has a ton of internal details that make it super hard to choreograph all this too. It has it's own internal lifecycle, and if it's not catered to just right, you get churn in your pub/subs.

We used to do a ton of work to keep the initial computation from first render alive, using timeouts, and checking things in useEffect - but it was horrendously difficult to maintain, and there were still many edge cases where it'd fail (in some cases causing subscriptions to die, and other to churn in a subscribe/unsubscribe death loop).

I'm actually thinking this is a bug in Meteor.defer - can you confirm whether it's *ever* run? I think it's not actually getting run in this case - that could be big bug in Meteor.defer that should be fixed on that side of this.

**Comment by CaptainN** [comment]
Actually, maybe we don't even need that defer? We might be able to take a page out of `useTrackerNoDeps` and simply call stop inline when the component hasn't yet been "mounted". I'll play around with that later.

**Comment by ksinas** [comment]
I'm not exactly sure how concurrent mode works under the hood, but I would be surprised that it would evaluate useMemo multiple times with the same deps. That sounds like a potential performance issue.

**Comment by CaptainN** [comment]
It definitely does - useMemo is just run inline with the rest of the render, and if the render is suspended, it's values are discarded. (I've seen some assertions that useRef is shared between renders in concurrent mode - but I don't think it is.) The individual "concurrently" rendered passes do not share any state between them.

**Comment by ksinas** [comment]
> It definitely does - useMemo is just run inline with the rest of the render, and if the render is suspended, it's values are discarded. (I've seen some assertions that useRef is shared between renders in concurrent mode - but I don't think it is.) The individual "concurrently" rendered passes do not share any state between them.

I played a bit around and can confirm that indeed, useMemo is called multiple times and refs are not shared. So that means that in concurrent mode might be multiple subscribe / unsubscribe happening. I guess it's safer to do subscriptions purely in useEffect

**Comment by CaptainN** [comment]
@ksinas Some things changed in ` 2.3.1` can you confirm whether or not this is still an issue in ` 2.3.1`?

**Comment by CaptainN** [comment]
@mfen I've committed this to the useFind branch, which currently represents the next release branch (2.4). So this will be in the next release.

Also, I can't reuse the initial computation as it turns out. The two have differing requirements. Not a big deal, but wanted to close that door.

**Comment by jorgeer** [comment]
I cloned the latest beta as I have been experiencing the same issue of sub-unsub-sub, and the latest PR does not seem to fix it for me unfortunately. I will try making a reproduction.

**Comment by CaptainN** [comment]
An update: This was resolved in the specific reported case by [supplying deps to `useTracker`](https://github.com/jorgeer/react-meteor-data-double-sub/issues/1) - however, this issue may expose a real bug that should be investigated with the "depsless" implementation of `useTracker`.

**Comment by henriquealbert** [comment]
Any updates on this one @CaptainN, or can we close it?

**Comment by CaptainN** [comment]
I think we are waiting on word from @ksinas ? I think this is fixed though.

**Comment by stevengragg** [comment]
Hello, I am experiencing the same issue. I am hoping this is related. Any luck on solving this?

![image](https://user-images.githubusercontent.com/70889203/191679638-6dfe14c0-b7c6-48b8-9092-3d21835211ce.png)
![image](https://user-images.githubusercontent.com/70889203/191679643-304c7e99-31ca-4001-afa5-98d0c17a4b16.png)
